[project]
name = "correlations-after-coffee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.2",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "ruff>=0.15.4",
]
